### PR TITLE
Fix #286 put idValidator before authorization

### LINKED ISSUE #286: Place idValidator middleware before all authorization middleware
The `RouteParam.idValidator` should be before `ensureAuthorized` so that there is not a 500 error when the user enters in an invalid id.

_Originally posted by @pierreTklein in https://github.com/hackmcgill/hackerAPI/pull/285_

### PR DESCRIPTION
**Pull request by Ty-Won**
# Description

Moving the idValidator before the authorization middleware

Fixes # 286

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
TBH not sure how to run the tests, first issue so please lemme know

# Checklist:

- [ ] My code follows the style guidelines of this project (Not sure)
- [x] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by krubenok** [comment]
@Ty-Won you can run the tests with `npm run test`. Just make sure you have a local mongo server running on your computer and have seeded the database (`npm run seed`).

TravisCI also runs those same tests on every PR (you passed 🎉!).

**Comment by Ty-Won** [comment]
@krubenok thanks Kyle, is there a specific linter and formater that the team uses?

**Comment by krubenok** [comment]
> @krubenok thanks Kyle, is there a specific linter and formater that the team uses?

Yes, there is a kinda stale PR that addressed this in #311

**Comment by pierreTklein** [comment]
Any update on this? If you can’t get the longer to work, we can try to turn off the linter + manually change back these edits for this PR.

**Comment by Ty-Won** [comment]
Yep! Totally slipped my mind and I was out of town for a bit. I can re-adjust the format after work

**Comment by Ty-Won** [comment]
Hey, so I made the most manual changes I could and I changed the spacing so hopefully that removes a lof of the false changes. I was using prettifier before perhaps that was the issues? If you guys are using prettier, maybe sharing the config file with the team to make a formatting consistent would be cool :sunglasses:  lemme know if there are any other changes

**Comment by Ty-Won** [comment]
@pierreTklein Hey Theo, Yep this is the most recent version of the work for this issue :)

**Comment by pierreTklein** [comment]
I still see the formatting changes, but if you want to commit it, go ahead

**Pull request merged**
