### PR TITLE
Switch to eslint and prettier for code formatting

### PR DESCRIPTION
**Pull request by loreina**
### Tickets:

- HCK-158
- Closes #311 

### List of changes:

I took stale PR #311 and updated with different eslint config + added prettier. When merged, we should start running `npm run format` and `npm run lint` before making PRs.

- Remove jshint and jslint
- Add eslint
- Add prettier
- Add format and lint scripts
  - `npm run format` runs prettier and formats code
  - `npm run lint` runs eslint and lints code
- Ran eslint
- Ran prettier

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?

I ran all the tests and everything passes. Main things are going from space --> tabs and enforcing single quote.

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pierreTklein** [comment]
Do we want to change " to '? Do we also want to change to 2 spaces instead of 4 spaces? Though I agree that we should have some unity to our files, I would like to make sure that these changes are relatively minimal and conform to the existing coding styles.

**Comment by loreina** [comment]
@pierreTklein tbh I was just following what the vscode and eslint settings were from before. if you prefer 4 spaces and double quotes, I can update it to that

**Comment by pierreTklein** [comment]
SGTM

**Comment by loreina** [comment]
@pierreTklein updated the config, let me know what you think 🙂

**Pull request merged**
